package br.gov.anatel.provaconceitoseam.domain;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import br.com.diegosilva.infraseam.entity.DefaultEntity;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name = "Nota")
@Audited
public class Nota extends DefaultEntity<Integer> {

	/**
	 * Variavel serialVersionUID do tipo long.
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", referencedColumnName = "id", nullable = false)
	@NotNull
	private Usuario usuario;

	@Column(name = "titulo", length = 100)
	@Length(max = 100)
	private String titulo;

	@Lob
	@Column(name = "texto")
	private String texto;

	public Nota() {
	}

	public Nota(Usuario usuario) {
		this.usuario = usuario;
	}

	public Nota(String titulo, String texto) {
		this.titulo = titulo;
		this.texto = texto;
	}

	public Nota(Usuario usuario, String titulo, String texto) {
		this.usuario = usuario;
		this.titulo = titulo;
		this.texto = texto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Override
	public int hashCode() {
		int hash = 0;
		hash += (getId() != null ? getId().hashCode() : 0);
		return hash;
	}

	/**
	 * @see br.gov.anatel.arquitetura.referencia.util
	 *      .common.BaseObject#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object object) {
		if (!(object instanceof Usuario)) {
			return false;
		}
		Usuario other = (Usuario) object;
		if ((this.getId() == null && other.getId() != null)
				|| (this.getId() != null && !this.getId().equals(other.getId()))) {
			return false;
		}
		return true;
	}

}
